name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * TUE'

jobs:
  Lint:
    name: Lint docker files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint docker files
        uses: docker://cdssnc/docker-lint

  Socket-Tunnel:
    name: Socket Tunnel
    needs: [Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build . --file Dockerfile --target socket-tunnel --tag matthewbaggett/tunnel:socket
      - name: Publish to Registry
        run: docker push matthewbaggett/tunnel:socket

  MySQL-Tunnel:
    name: MySQL Tunnel
    needs: [Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build . --file Dockerfile --target mysql-tunnel --tag matthewbaggett/tunnel:mysql
      - name: Publish to Registry
        run: docker push matthewbaggett/tunnel:mysql

  Redis-Tunnel:
    name: Redis Tunnel
    needs: [Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build . --file Dockerfile --target redis-tunnel --tag matthewbaggett/tunnel:redis
      - name: Publish to Registry
        run: docker push matthewbaggett/tunnel:redis
